### ISSUE TITLE
ifClicked event is actually ifClicking?

### ISSUE THREAD

**Issue by tianxu0836** [drgullin/icheck#141]
For the checkbox, ifClicked event fires before the check status changed.

Plus, ifToggled event fires when I call check/uncheck the cbox in the code. Is there any event that fires only if user toggled not the code toggled it?

Now, If I want to post the check status to the server after user uncheck/check the cbox, and when I load the page, I want to get the cbox check status and check the cbox in the code without post to the server again. How should I do that?

**Comment by drgullin** [comment]
There's no reliable way to know if a state was changed by user or code.
You can change a state directly and call `update` method using the code like:

```
$('input').each(function() {
  this.checked = false;
}).iCheck('update');
```

To get a cbox status on a page load, you can use `ifCreated` callback (disabled by default in 2.x). This one fires immediately after customization:

```
$('input').on('ifCreated', function(event) {
  // console.log(this.checked);
});
```

Btw, I recommend to use a 2.x version, since it's much better than the 1.x branch.

**Comment by tianxu0836** [comment]
After I update to 2.x version, it complaining that "$(input).icheck is not a function", I spent 15min, not sure why. I'm kind of lose patient.

I doubt if it really worth to spend long time to change everywhere in my code to make it work for 2.x version. It seems everything is change.

**Comment by tianxu0836** [comment]
Could you pls provide a jsfiddle for 2.x version.
I can't event initialize it, that is ridiculous

**Comment by drgullin** [comment]
What about `$('input').icheck()`?

Be careful with the methods names in 2.x. Almost all other things are unchanged.

See https://github.com/fronteed/iCheck/blob/2.x-beta/README.md

**Comment by tianxu0836** [comment]
pls try this. I'm not sure what I missed.
if I use 1.0 version it works
if I use 2.0 version it doesn't work
http://jsfiddle.net/tianxu0836/5NBWa/2/

$('input').icheck() doesn't work and it complains that "icheck is not a function"

**Comment by drgullin** [comment]
I guess it doesn't work because you include the iCheck plugin directly from `raw.github.com`

Github serves scripts with mime type `text`, not `javascript`.
So the included script at jsfiddle is only a text. As a result, there's no `icheck` function.

**Comment by tianxu0836** [comment]
I have iCheck plugin on my local, I'm not using the plugin directly from raw.github.com on my local.
The way I'm including iCheck is correct. 

1.x version works but 2.x version doesn't work.

Here is my code to initialize icheck:
  $('input').icheck({
    checkboxClass: 'icheckbox_square'
  });

It throws this error: "TypeError: win.icheck is undefined"
line 961:
"if (win.icheck.autoInit) {"

**Comment by drgullin** [comment]
It should work now, check it out.

**Comment by Johntravalgar** [comment]
nice article ...
please visit - Point Of Sale http://goo.gl/h4PWmB

**Comment by talengix** [comment]
same issue for me. with 2.0 i get the iCheck is not a function error.

**Comment by irfan-yusanif** [comment]
Same issue! Everything works fine with 1.0 version. But in 2.0 version i get the error: $(...).iCheck is not a function

**Comment by danribeiro** [comment]
Hi! 

Same issue!, 2.0 version i get the error: $(...).iCheck is not a function.
