### ISSUE TITLE
icheck is not a function error on updating to 2.0

### ISSUE THREAD

**Issue by irfan-yusanif** [drgullin/icheck#334]
`$('.i-check').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
`
Everything is working fine with 1.0 version. But on updating to 2.0 version i'm getting error 

> icheck is not a function

**Comment by irfan-yusanif** [comment]
The issue is with `icheck` and `iCheck` version 1 uses `iCheck` while version 2 uses `icheck`. Now I just changed `iCheck` to `icheck` and it works fine :)
